- name: install apache & php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest


- name: change admin email in apache config
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin eehsane@example.com
  when: ansible_distribution == "Ubuntu"
  # its a variable, name can be anything
  notify: apache_restart_handler

