---

- hosts: all
  become: true 
  tasks: 
  
  - name: install apache and php
    # package is module that automatically detect underlying host package-manager
    package:
      name: # variables are defined in inventory
        - "{{ apache_package }}"
        - "{{ php_package }}"
    update_cache: true

