---

- hosts: all
  become: true
  tasks:

  - name: update ubuntu servers
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base
